export const pantry = [
  'Alaska Pollock',
  'Albacore',
  'Alfalfa Sprouts',
  'Allspice',
  'Almond Flour',
  'Almond Milk',
  'Almonds',
  'Anchovy',
  'Apple',
  'Apple Juice',
  'Apple Vinegar Cider',
  'Apricot',
  'Artichoke',
  'Asparagus',
  'Baby Carrot',
  'Baby Spinach',
  'Bacon',
  'Baking Powder',
  'Balsamic Vinegar',
  'Bamboo Shoot',
  'Banana',
  'Barley',
  'Basil',
  'Basmati Rice',
  'Bay Leaf',
  'Beef',
  'Beef Bouillon',
  'Beef Broth',
  'Beef Stock',
  'Beer',
  'Beetroot',
  'Beetroot Juice',
  'Berries',
  'Biscuit',
  'Black Beans',
  'Black Olive',
  'Black Tea',
  'Blackberry',
  'Blueberry',
  'Bran',
  'Brandy',
  'Brazil Nuts',
  'Bread Crumbs',
  'Broccoli',
  'Brown Beans',
  'Brown Lentils',
  'Brown Rice',
  'Brown Sugar',
  'Brussel Sprouts',
  'Butter',
  'Butterleaf Lettuce',
  'Buttermilk',
  'Camomile',
  'Cane Sugar',
  'Cane Syrup Sugar',
  'Canola Oil',
  'Capers',
  'Caramel Syrup',
  'Carbonated Water',
  'Carrot',
  'Carrot Juice',
  'Cashews',
  'Cauliflower',
  'Cayenne Pepper',
  'Celeriac',
  'Celery',
  'Celery Seed',
  'Cereal',
  'Champignon',
  'Chard',
  'Cheddar Cheese',
  'Cheddar Sharp Cheese',
  'Cherry',
  'Cherry Tomatos',
  'Chestnut',
  'Chicken',
  'Chicken Breast',
  'Chicken Broth',
  'Chicken Thigh',
  'Chickpea',
  'Chicory',
  'Chili Pepper',
  'Chives',
  'Chocolate',
  'Chocolate	Milk',
  'Chocolate	Syrup',
  'Chocolate Pudding',
  'Chorizo',
  'Cider Vinegar',
  'Cinnamon',
  'Cinnamon Powder',
  'Cinnamon Sticks',
  'Clementine',
  'Clove',
  'Cocoa',
  'Cocoa Bean',
  'Cocoa Butter',
  'Cocoa Powder',
  'Coconut',
  'Coconut Milk',
  'Coconut Oil',
  'Coconut Water',
  'Cod',
  'Coffee',
  'Cognac',
  'Condensed Milk',
  'Coriander',
  'Corn',
  'Corn Flour',
  'Corn Starch',
  'Corn Syrup',
  'Corn Tortillas',
  'Cottonseed Oil',
  'Crab',
  'Cracked Black Pepper',
  'Cranberry',
  'Cream',
  'Crème Fraîche',
  'Crushed Tomatos',
  'Cucumber',
  'Cumin',
  'Curry',
  'Curry Powder',
  'Dark Chocolate',
  'Date',
  'Dijon Mustard',
  'Dill',
  'Dragonfruit',
  'Dried Apple',
  'Dried Apricots',
  'Dried Cranberries',
  'Duck',
  'Egg',
  'Egg White',
  'Egg Yolk',
  'Elderberry',
  'Elderberry Juice',
  'Extra Virgin Olive Oil',
  'Fennel',
  'Fennel Seed',
  'Fetuccini Pasta',
  'Feta',
  'Fig',
  'Fish Sauce',
  'Flax',
  'Flax Seed',
  'Flour',
  'Fruit Pectin',
  'Garlic',
  'Garlic Paste',
  'Garlic Powder',
  'Garlic Salt',
  'Ginger',
  'Ginger Powder',
  'Gingerbread',
  'Glaze',
  'Goat Cheese',
  "Goat's Milk",
  'Gouda',
  'Grape Juice',
  'Grapefruit',
  'Grapefruit Juice',
  'Green Bean',
  'Green Bell Pepper',
  'Green Cabbage',
  'Green Grape',
  'Green Lentils',
  'Green Olive',
  'Green Peas',
  'Green Tea',
  'Guava',
  'Habanero Chili',
  'Ham',
  'Hazelnut',
  'Herring',
  'Himalayan Salt',
  'Honey',
  'Ice',
  'Ice Cream',
  'Iceberg Lettuce',
  'Icing Sugar',
  'Jalapeno',
  'Ketchup',
  'Kidney Beans',
  'Kiwi',
  'Lamb',
  'Lemon',
  'Lemon Juice',
  'Lemongrass',
  'Light Cream',
  'Lime',
  'Lime Juice',
  'Linguini Pasta',
  'Liquorice',
  'Lobster',
  'Long Grain Rice',
  'Low Fat Milk',
  'Low Fat Yogurt',
  'Mackerel',
  'Malt',
  'Mandarin',
  'Mango',
  'Margarine',
  'Marigold',
  'Marjoram',
  'Marshmallow',
  'Mascarpone',
  'Mayonnaise',
  'Melon',
  'Milk Chocolate',
  'Mint',
  'Molasses',
  'Mozzarella Cheese',
  'Mushroom',
  'Mustard',
  'Mustard Seed',
  'Nectarine',
  'Nettle',
  'Nutmeg',
  'Oat',
  'Oat Flour',
  'Oat Milk',
  'Olive Oil',
  'Olive Virgin Oil',
  'Omelette',
  'Onion',
  'Onion Powder',
  'Orange',
  'Orange Juice',
  'Oregano',
  'Papaya',
  'Paprika',
  'Parmesan',
  'Parsley',
  'Parsnip',
  'Passion Fruit',
  'Passion Fruit Juice',
  'Peach',
  'Peach Juice',
  'Peanut',
  'Pear',
  'Pear Juice',
  'Peas',
  'Pecans',
  'Pepper',
  'Pepper Extract',
  'Pepperjack Cheese',
  'Peppermint',
  'Pickles Flavour',
  'Pine Nuts',
  'Pineapple',
  'Pineapple Juice',
  'Pinto Beans',
  'Pistachios',
  'Plantain',
  'Plum',
  'Poppy Seed',
  'Pork Sausage',
  'Potato',
  'Powdered Sugar',
  'Prune',
  'Pumpkin',
  'Pumpkin Seed',
  'Pure Vanilla Extract',
  'Quail',
  'Quinoa',
  'Radish',
  'Raisin',
  'Raspberry',
  'Raspberry Juice',
  'Ravioli',
  'Red Bell Pepper',
  'Red Cabbage',
  'Red Grape',
  'Red Wine',
  'Redcurrant',
  'Rice',
  'Rice Pudding',
  'Ricotta',
  'Rigatoni Pasta',
  'Rigatoni Pasta',
  'Roasted Peanuts',
  'Romaine Lettuce',
  'Rose Hip',
  'Rosé Wine',
  'Rosemary',
  'Rum',
  'Rye Bread',
  'Rye Flour',
  'Sage',
  'Salami',
  'Salmon',
  'Salt',
  'Salted Butter',
  'Salted Butter Caramel',
  'Sardine',
  'Scallop',
  'Sea Salt',
  'Seaweed',
  'Shallot',
  'Shea Butter',
  'Shea Oil',
  'Shiitake',
  'Shrimp',
  'Skipjack Tuna',
  'Sliced Almond',
  'Smoked Bacon',
  'Sour Cream',
  'Sourdough Bread',
  'Soy Milk',
  'Soy Sauce',
  'Spaghetti Pasta',
  'Spinach',
  'Split Peas',
  'Squid',
  'Star Anise',
  'Starch',
  'Strawberry',
  'Strawberry Juice',
  'Sundried Tomatos',
  'Sunflower Seed',
  'Tahini',
  'Tamarind',
  'Tapioca Pudding',
  'Thin Spaghetti Pasta',
  'Thyme',
  'Tofu',
  'Tomato Juice',
  'Tomato Sauce',
  'Tomatos',
  'Tri Tip',
  'Tuna',
  'Turkey',
  'Turkey Breast',
  'Turmeric',
  'Turmeric Powder',
  'Unsalted Butter',
  'Vanilla',
  'Vanilla Extract',
  'Vanilla Pod',
  'Vanilla Pudding',
  'Veal',
  'Vegetable Broth',
  'Vegetable Oil',
  'Vermouth',
  'Vinaigrette',
  'Vinegar',
  'Walnut',
  'Water Chestnut',
  'Watermelon',
  'Wheat',
  'Wheat Flour',
  'Wheat Germ',
  'Whipped Cream',
  'Whipping Cream',
  'White Bread',
  'White Cabbage',
  'White Chocolate',
  'White Grape',
  'White Rice',
  'White Tea',
  'White Wine',
  'Whole Almond',
  'Whole Milk',
  'Whole Weat Bread',
  'Whole Wheat Flour',
  'Wild Rice',
  'Yeast',
  'Yellow Bell Pepper',
  'Yellowfin Tuna',
  'Yogurt',
]
